version: "3.9"
services:
  usr:
    build: .
    privileged: true
    stop_grace_period: 1s
    cap_add:
      - NET_ADMIN
    depends_on:
      - "r1"
      - "r2"
    volumes:
      - ./user:/app
      - ./shared:/shared
    networks:
      - usrnet
  r1:
    build: .
    privileged: true
    stop_grace_period: 1s
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
    volumes:
      - ./router:/app
      - ./shared:/shared
    networks:
      usrnet:
        priority: 100
        ipv4_address: 172.20.10.2
      backbone:
        priority: 1000
        ipv4_address: 172.20.250.2
  r2:
    build: .
    privileged: true
    stop_grace_period: 1s
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
    volumes:
      - ./router:/app
      - ./shared:/shared
    networks:
      srvnet:
        priority: 100
        ipv4_address: 172.20.20.2
      backbone:
        priority: 1000
        ipv4_address: 172.20.250.3
  srv:
    build: .
    privileged: true
    stop_grace_period: 1s
    cap_add:
      - NET_ADMIN
    depends_on:
      - "r1"
      - "r2"
    volumes:
      - ./server:/app
      - ./shared:/shared
    networks:
      - srvnet

networks:
  backbone:
    internal: false
    ipam:
      config:
        - subnet: 172.20.250.0/24
  usrnet:
    internal: false
    ipam:
      config:
        - subnet: 172.20.10.0/24
  srvnet:
    internal: false
    ipam:
      config:
        - subnet: 172.20.20.0/24
