version: "3.9"
services:
  usr:
    build: .
    privileged: true
    stop_grace_period: 1s
    cap_add:
      - NET_ADMIN
    depends_on:
      - "router-qdisc"
    volumes:
      - ./users:/app
      - ./shared:/shared
    networks:
      - usrnet
  router-qdisc:
    build: .
    privileged: true
    stop_grace_period: 1s
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
    depends_on:
      - "router-congestion"
    volumes:
      - ./router:/app
      - ./shared:/shared
    networks:
      usrnet:
        ipv4_address: 172.20.10.2
      routernet:
        ipv4_address: 172.20.11.2
  router-congestion:
    build: .
    privileged: true
    stop_grace_period: 1s
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
    volumes:
      - ./router:/app
      - ./shared:/shared
    networks:
      routernet:
        ipv4_address: 172.20.11.3

networks:
  usrnet:
    internal: false
    ipam:
      config:
        - subnet: 172.20.10.0/24
  routernet:
    internal: false
    ipam:
      config:
        - subnet: 172.20.11.0/24
